name: Build and Release EXE

on:
  push:
    tags:
      - "v*.*.*" # Triggers on v1.0.0, v2.1.3, etc.

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyinstaller
          # Add your requirements.txt if you have one
          # python -m pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --windowed --name="AWS_EC2_VPN" --distpath=dist Client/main.py

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $env:GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: AWS EC2 VPN ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Download
            Download `AWS_EC2_VPN.exe` below to get started.

            ## Changes
            - Built from commit: ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/AWS_EC2_VPN.exe
          asset_name: AWS_EC2_VPN_${{ steps.get_version.outputs.VERSION }}.exe
          asset_content_type: application/octet-stream
