name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Debug Deploy
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Testing connection to $HOST as $USER"
          echo "$KEY" > key.pem
          chmod 600 key.pem

          # Debug: Check key format
          echo "Key first line:"
          head -n 1 key.pem

          # Test connection with verbose output
          ssh -vv -o StrictHostKeyChecking=no -i key.pem ${USER}@${HOST} "echo 'Connection successful!'" || true

          # If that fails, try converting key format
          ssh-keygen -p -m PEM -f key.pem -N "" || true

          # Try again
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER}@${HOST} "echo 'Connection successful after conversion!'" || true

          rm key.pem
